name: Continous Deployment

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps: 
      - uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH }} 
      - run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
      - run: ssh -t root@cordfuck.com 'cd /var/www/cordfuck ; git reset --hard origin/main'
