name: Continous Deployment

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps: 
      - uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH }} 
          known_hosts: "foobar"
      - run: ssh-keyscan -H 217.182.253.173 >> ~/.ssh/known_hosts
      - run: ssh -t -T root@217.182.253.173 'cd /var/www/cordfuck ; git reset --hard origin/main ; exit'
