name: Continous Deployment

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: appleboy/ssh-action@master
        with:
          host: 217.182.253.173
          username: root
          key: ${{ secrets.SSH }}
          port: 22
          script: |
            cd /var/www/cordfuck
            git reset --hard